version: '3.7'

services:
  mf-traefik:
    image: traefik:2.9.4
    container_name: mf-traefik
    command: --api.insecure=true --providers.docker=true
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mf
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.mf`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080

networks:
  mf:
    external: true
