---

name: Development

on:
  push:
    branches:
      - dev

jobs:
  deliver:
    runs-on: 
      - self-hosted
      - development
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Start
        run: |
          docker compose build
          docker compose down
          docker compose up -d
